module.exports = {
    USER_REGISTER: '0',
    USER_DELETE_USER: '1',
    USER_UPDATE_USER: '2',
    USER_ADD_PRODUCT: '3',
    USER_UPDATE_PRODUCT: '4',
    USER_DELETE_PRODUCT: '5',
    USER_FORGOT_UPDATE_PRODUCT: '6'
};
